name: park_app
description: A new Flutter project.

publish_to: 'none' 

version: 0.3.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.3
  mobile_scanner: ^2.0.0
  flutter_map: ^2.0.0
  geojson: ^1.0.0
  latlong2: ^0.8.1
  provider: ^6.0.0
  intl: ^0.17.0
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15
  location: ^4.4.0
  sqflite: ^2.0.2+1
  path_provider: ^2.0.11
  animated_splash_screen: ^1.2.0
  animated_text_kit: ^4.2.2
  path: ^1.8.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/app_data.db
    
 
  fonts:
    - family: MavenPro
      fonts:
        - asset: assets/fonts/Maven.ttf
    - family: TrajanPro
      fonts:
        - asset: assets/fonts/Trajan.otf

flutter_intl:
  # Required. Must be set to true to activate the plugin.
  enabled: true # Default: false
  # Optional. Sets the name for the generated localization class.
  class_name: Localized # Default: S
  # Optional. Sets the main locale used for generating localization files.
  # Provided value should consist of language code and optional script and country codes
  # separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN').
  main_locale: en # Default: en
  # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system.
  arb_dir: lib/src/common/localization # Default: lib/l10n
  # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system.
  output_dir: lib/src/common/localization # Default: lib/generated
  # Optional. Must be set to true to generate localization code that is loaded with deferred loading.
  use_deferred_loading: false # Default: false